// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tHCRlQG5m6pLubGsr_N6efgyoRQUCks',
    appId: '1:924080130144:web:020a7471ddddccc07c1b05',
    messagingSenderId: '924080130144',
    projectId: 'spoti-app-2f8ff',
    authDomain: 'spoti-app-2f8ff.firebaseapp.com',
    storageBucket: 'spoti-app-2f8ff.firebasestorage.app',
    measurementId: 'G-5BV6T04N03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp31mShtU6MJh8dQ5A4qZKOopQi1xS2-M',
    appId: '1:924080130144:android:12dc4045f8c0e7ac7c1b05',
    messagingSenderId: '924080130144',
    projectId: 'spoti-app-2f8ff',
    storageBucket: 'spoti-app-2f8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0JS4hrG_sl1nHaTzFAEbcw3FIgUBQFs',
    appId: '1:924080130144:ios:f519548d684cbd1f7c1b05',
    messagingSenderId: '924080130144',
    projectId: 'spoti-app-2f8ff',
    storageBucket: 'spoti-app-2f8ff.firebasestorage.app',
    iosClientId: '924080130144-do25r2u7f2mo7aa9q6msp7kjpi4i8u61.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq0JS4hrG_sl1nHaTzFAEbcw3FIgUBQFs',
    appId: '1:924080130144:ios:f519548d684cbd1f7c1b05',
    messagingSenderId: '924080130144',
    projectId: 'spoti-app-2f8ff',
    storageBucket: 'spoti-app-2f8ff.firebasestorage.app',
    iosClientId: '924080130144-do25r2u7f2mo7aa9q6msp7kjpi4i8u61.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tHCRlQG5m6pLubGsr_N6efgyoRQUCks',
    appId: '1:924080130144:web:458bdc2ab46ba03e7c1b05',
    messagingSenderId: '924080130144',
    projectId: 'spoti-app-2f8ff',
    authDomain: 'spoti-app-2f8ff.firebaseapp.com',
    storageBucket: 'spoti-app-2f8ff.firebasestorage.app',
    measurementId: 'G-FHHWRZXHDF',
  );
}
